name: command_line_solitaire
description: A command-line implementation of the Klondike Solitaire game, written in dart.
version: 1.1.0
repository: https://github.com/ntatko/solitaire-cmd

executables:
  solitaire: command_line_solitaire

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
